### ISSUE TITLE
Blatt 9 - Codeerzeugung

### ISSUE THREAD

**Issue by iTob191** [compilerpraktikum/compiler#105]
- #76 
- #101 
- Codeerzeugung
  - [x] Zwischensprache(n?): für [molki](https://git.scc.kit.edu/IPDSnelting/molki) @iTob191 
  - [x] SSA-Abbau (wann?)
  - [x] #109
  - [x] Befehlsanordnung
  - [x] Register-"Allokation" @Cydhra

**Comment by 9dm** [comment]
Zwischensprache mit Datentyp für Register statt Strings
