### ISSUE TITLE
Blatt 4 - AST

### ISSUE THREAD

**Issue by iTob191** [compilerpraktikum/compiler#42]
- [x] Aufgabe 1.1: Abstrake Algebra @iTob191 @RobinRSchulz #46 
- [x] Aufgabe 1.3: Attributierte Grammatik @iTob191 @RobinRSchulz #46
- [x] AST implementieren
  - [x] error nodes @csicar 
- [x] Aufgabe 2: PrettyPrinter @RobinRSchulz @9dm 
  - [x] Tests: Idempotenz, korrekte Klammerung (-> Assoziativität)

Außerdem:
- [x] Error handling @iTob191 @csicar 
  - [x] ~~Eigene Exceptions~~ Gar keine Exceptions (sonst tut wiederaufsetzen nicht)
  - [x] #59
  - [x] Error Reporting #54 
  - [x] Korrekte Return Codes!
- [x] Ankermengen @Cydhra 
  - [x] Fehlende First/Follow Mengen berechnen
  - [x] Compilerbauvorlesung Übung 3 für tolle Extras: https://pp.ipd.kit.edu/lehre/SS2021/compiler/uebung/intern/parser.zip -> parser.c -> add_anchor / add_follow
  - [x] Implementation
  - [x] Generieren des Lenient AST #53 
- [x] Async zu Sync umarbeiten @iTob191 -> #44
