### ISSUE TITLE
Blatt 5 - Semantische Analyse

### ISSUE THREAD

**Issue by iTob191** [compilerpraktikum/compiler#57]
- [x] #42 fertig machen
- [x] **Namensanalyse** #80 @iTob191 @9dm
  - [x] #61 @iTob191
  - [x] **Ergebnisse in AST (Verlinkung zu Definition)**
  - [x] **Fehler, falls Namens-Auflösung nicht erfolgreich**
- [x] **Typ-Prüfung** @csicar @9dm @RobinRSchulz
  - [x] `void[]` ablehnen
- [x] #60
- [x] **`--check` implementieren** @iTob191 
- [x] **MJ-Test: 5 semantisch korrekte + 5 syntaktisch korrekte, semantisch falsche Programme (Deadline: 18.11.)** @9dm
- [x] Error messages für semantische Analyse erweitern @iTob191 

Legende: **Pflicht**, optional
