### ISSUE TITLE
Blatt 6 + 7 - Firm-Graph

### ISSUE THREAD

**Issue by iTob191** [compilerpraktikum/compiler#76]
- #42 -> #59 @csicar @Cydhra 
- #57 
- Tests @9dm 
  - [x] 2x1 Tests von Blatt 5 (letzte Woche) nachreichen
  - [x] 1x5 Tests von Blatt 7 (Deadline: 2.12.)
- [x] (j)Firm integrieren @Cydhra 
- AST in Firm "übersetzen"
  - [x] Typen + Entities: Primitive, Methoden-Typen, Klassen-Typen @iTob191 
  - Methoden
    - [x] Parameter
    - [x] Ausdrücke: literals, arithmetic, local variables / parameters, field/array access (-> load/store), call, new
    - [x] boolsche Ausdrücke mit Kurzauswertung
    - [x] Vergleiche
    - [x] Kontrollfluss: if, while
    - [x] Runtime-Lib in Compiler / Firm-Graph einbinden
- [x] #93
- [X] ~~Nächstes ÜB anfangen: Optimierungen~~ -> Ausgelagert nach: #101 @RobinRSchulz
- [x] Visitor aufräumen: alle Branches müssen `return` haben (oder keiner) @RobinRSchulz 
- [x] SourceRanges testen @csicar
- [x] #95
- [x] Lowering: Sel-Knoten in Adressrechnung umwandeln (-> see `Lower.java` aus jFirm) #98  @9dm
- [x] Code-Generation mit Firm-Backend @9dm
- [x] `--compile-firm` implementieren @iTob191 
- [x] MJTest integrieren @iTob191
